version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore -verbosity quiet
build:
  parallel: true
  verbosity: minimal
test_script:
- ps: .\run-tests.ps1
artifacts:
- path: NuGetBuild/Stamp.Fody.*.nupkg
  name: nuget