version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore -verbosity quiet
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: NuGetBuild/Stamp.Fody.*.nupkg
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: oVrrIFIVUfUpR9RRH/QYKkmR7fOuu0JY29ok9RbbhjWt5o9CS6Q8pNu67701hLuQ
  artifact: /.*\.nupkg/
  on:
    branch: master